### ISSUE TITLE
how to configure .. ?!

### ISSUE THREAD

**Issue by lebeck69** [darrylb123/ESP32_SMA-Inverter-MQTT#5]
sorry if it's not a issue but just me not understanding .. but i don't really get how to configure your code.

I'm using VS code and have the following errors : 

- in config_exemple.h > identifier “uint8_t” is undefined
- in config.h > cannot open source file for all ‘include’ like wifi.h

I'll try to put that on a ESP and I usually see some board code like those
[env:m5stack-core-esp32]
platform = espressif32
board = m5stack-core-esp32

**Comment by darrylb123** [comment]
Sorry, didn't see this issue open. Grab this fork for the moment. We will be merging into one. I've successfully built using this fork. https://github.com/keerekeerweere/ESP32_SMA-Inverter-MQTT

**Comment by darrylb123** [comment]
Ok, the fork has been merged.
You should be able to pull the merge and build it.
