### ISSUE TITLE
Which program to build and upload, VScode and Gitpod error.

### ISSUE THREAD

**Issue by kommando828** [darrylb123/ESP32_SMA-Inverter-MQTT#8]
Having an issue trying to get this to build using VS Code, In PIO home I get this error highlighted in bold.

Compiling .pio\build\espwroom32\lib175\WiFi\WiFiScan.cpp.o
In file included from src/ESP32_SMA_Inverter_App.cpp:26:

> __src/ESP32_SMA_Inverter_App.h:9:10: fatal error: TBPubSubClient.h: No such file or directory__

************************************************************************
* Looking for TBPubSubClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:TBPubSubClient.h"
* Web  > https://registry.platformio.org/search?q=header:TBPubSubClient.h
*
************************************************************************

 #include <TBPubSubClient.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\espwroom32\src\ESP32_SMA_Inverter_App.cpp.o] Error 1
In file included from src/ESP32_SMA_MQTT.h:20,
                 from src/ESP32_SMA_MQTT.cpp:25:
**src/ESP32_SMA_Inverter_App.h:9:10: fatal error: TBPubSubClient.h: No such file or directory**

************************************************************************
* Looking for TBPubSubClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:TBPubSubClient.h"
* Web  > https://registry.platformio.org/search?q=header:TBPubSubClient.h
*
************************************************************************

 #include <TBPubSubClient.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\espwroom32\src\ESP32_SMA_MQTT.cpp.o] Error 1
=============================================================== [FAILED] Took 11.80 seconds 

Not sure if I should be using VS code and so get the error or there is another error. 

In Gitpod I get much the same error

In file included from src/ESP32_SMA_MQTT.h:20,
                 from src/ESP32_SMA_MQTT.cpp:25:
src/ESP32_SMA_Inverter_App.h:9:10: fatal error: TBPubSubClient.h: No such file or directory

************************************************************************
* Looking for TBPubSubClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:TBPubSubClient.h"
* Web  > https://registry.platformio.org/search?q=header:TBPubSubClient.h
*
************************************************************************

 #include <TBPubSubClient.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio/build/espwroom32/libc1e/FS/FS.cpp.o
*** [.pio/build/espwroom32/src/ESP32_SMA_Inverter_App.cpp.o] Error 1
Compiling .pio/build/espwroom32/libc1e/FS/vfs_api.cpp.o
*** [.pio/build/espwroom32/src/ESP32_SMA_MQTT.cpp.o] Error 1

The only change I have made is in platformio.ini where I have set the comms ports to COM[6], as I am using Win11 and the board is set to esp32dev as I have a Wroom32 and this same board type works with other projects. But even if I leave it as lolin_d32 I get the same error.
 file included from src/ESP32_SMA_MQTT.h:20,
                 from src/ESP32_SMA_MQTT.cpp:25:
s_rc/ESP32_SMA_Inverter_App.h:9:10: fatal error: TBPubSubClient.h: No such file or directory_

thanks in advance for looking.

**Comment by kommando828** [comment]
Seems a library is not working, these are said to be used but TBPubSubClient is corrupt on my PC or is no longer working 

Dependency Graph
|-- ArduinoJson @ 6.21.4
|-- **TBPubSubClient @ 2.9.3+sha.5b3177f**
|-- ESP32 logger @ 1.0.3+sha.f296e5d
|-- BluetoothSerial @ 2.0.0
|-- WebServer @ 2.0.0
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- LittleFS @ 2.0.0
|-- Preferences @ 2.0.0

**Comment by kommando828** [comment]
This is from platformio.ini

#knolleary/PubSubClient@^2.8

but the library being downloaded is 2.9.3 so maybe there is a mismatch and they are out of sync.

**Comment by kommando828** [comment]
Looks like the change from 2.9.2 to 2.9.3 has broken the link between PubSubClient.h and TBPubSubClient.h to be seen as one and the same files. The change notes refer to 2.9.3 as being supposed to fix this but looks to have had the opposite effect.

https://github.com/thingsboard/pubsubclient/releases

I went into ESP32_SMA_Inverter_App.h and edited TBPubSubClient.h to PubSubClient.h and  this change allowed the build to finish successfully.

**Comment by darrylb123** [comment]
Sorry, Just saw this issue. 
I had not used Vscode  for months and once everything updated I saw the same issue as you described and the fix was as you said. 
Thanks

**Comment by darrylb123** [comment]
Pushed new version with fix
